/**
 * PRD 011 Reqs 9+25: "who sends this, and as whom" — answered ONCE, by
 * capability rather than by flavor.
 *
 * Two questions live here because they have one answer between them: given the
 * area's resolved availability (`llmAreaState()`), which runner sends a request
 * (a hosted client server-side, a desktop transport through the seam, or
 * nothing at all), and which provider/model a cache key must therefore name.
 * Both the settings area's test connection and the zoom view's summaries call
 * these, so neither assembles a runner or a key context inline.
 *
 * Nothing here branches on `platform.kind` (`.sandcastle/CODING_STANDARDS.md`
 * § Architecture): the caller hands over whichever capabilities its window
 * holds, structurally, and this module reads the availability state.
 *
 * PRD 011 Req 34: pure. Selecting a runner sends nothing; the returned function
 * is what a caller invokes on behalf of a user action.
 */

import { runLlmRequest } from './llmSeam.ts';
// Imported as a block, not as inline `type` specifiers: U490 reads this tree
// for `type Llm(Request|Response)` to prove exactly one module DECLARES those
// shapes, and re-using them must not read as re-declaring them.
import type { LlmRequest, LlmResponse, LlmTransport } from './llmSeam.ts';
import type { LlmAreaState, LlmRunner } from './llmSettings.ts';
import type { SummaryKeyContext } from './summaryCache.ts';
import type { ZoomLevel } from './zoomLevels.ts';

/**
 * The capabilities a window may hold, structurally — `platform.llm` and
 * `platform.llmTransport`. Named by shape rather than imported from
 * `src/platform/`, which `src/lib/` may not reach.
 */
export interface LlmRunnerCapabilities {
  /** Hosted: the same-origin client that runs a request server-side. */
  hosted?: { run(request: LlmRequest): Promise<LlmResponse> } | null;
  /** Desktop: the transport the seam sends a built descriptor through. */
  transport?: LlmTransport | null;
}

/**
 * PRD 011 Req 9: the runner for this window, or null when nothing can send.
 * Hosted wins where a hosted client exists (the credential is the operator's);
 * otherwise a desktop transport plus a `ready` configuration is the only path.
 * Every other area state — no path, operator-unconfigured, unconfigured — has
 * no runner, which is exactly what the excerpt fallback (Req 22) keys off.
 */
export function selectLlmRunner(area: LlmAreaState, capabilities: LlmRunnerCapabilities): LlmRunner | null {
  if (area.state === 'hosted' && capabilities.hosted) {
    const client = capabilities.hosted;
    return (request) => client.run(request);
  }
  if (area.state === 'ready' && capabilities.transport) {
    const transport = capabilities.transport;
    return (request) => runLlmRequest(transport, area.config, request);
  }
  return null;
}

/**
 * PRD 011 Req 25: which `SummaryKeyContext` applies right now — the one place
 * the level, provider id and model id are put together. A hosted deployment
 * names the operator's provider and model; a ready desktop window names its own
 * configured pair. Changing either changes every key, so a summary generated by
 * a different model is never served as this one's.
 *
 * Null where nothing can send: there is no context in which to cache, and no
 * request to make.
 */
export function summaryKeyContextFor(area: LlmAreaState, level: ZoomLevel): SummaryKeyContext | null {
  if (area.state === 'hosted') return { level, providerId: area.provider, modelId: area.model };
  if (area.state === 'ready') return { level, providerId: area.config.kind, modelId: area.config.model };
  return null;
}
